### ISSUE TITLE
brillouin zone does not show a hexagon

### ISSUE THREAD

**Issue by obgeneralao** [dean0x7d/pybinding#1]
Hi,

I modified the primitive lattice vector as shown on the figure(in pdf)
[crystal_strucure.pdf](https://github.com/dean0x7d/pybinding/files/564561/crystal_strucure.pdf)

However I have trouble with the brillouin zone figure, the hexagon was missing
[brillouin_zone.pdf](https://github.com/dean0x7d/pybinding/files/564567/brillouin_zone.pdf)

My code is:
[the code.txt](https://github.com/dean0x7d/pybinding/files/564576/the.code.txt)

Thanks

P.S. I just bumped on your project 2 days ago and I am not good at Python programming but just a little above beginner and below average.

**Comment by dean0x7d** [comment]
Thank you for reporting the issue. Indeed, it seems to be a bug in the Brillouin zone calculation, specifically in cases where the angle between lattice vectors is obtuse. I have just committed some changes in a3aee7f8ae53f6fabe330b612d80091ee7bb3ed1 which should make this calculation more robust and fix the problem.

That fix is committed in the master branch, so you would need to compile the latest version from source code. This can be a bit more complicated than the normal install, but instruction on how to do that are here: [Compiling from source](http://docs.pybinding.site/en/latest/install/advanced.html#compiling-from-source). Note that the documentation has two versions: 1. stable (currently v0.8.0) and 2. latest (following the master branch).

Alternatively, you can wait for the release of the next version (v0.8.1) which will use the regular install procedure. I'm planning to add a few more bug fixes and release that soon.

**Comment by obgeneralao** [comment]
Terrific!  it works.

Though I did not compile it from source because I am getting a lot of errors, I am using Anaconda though. What I did was copy the lattice.py to Anaconda.

I appreciate it.

**Comment by dean0x7d** [comment]
Great, I'm glad to hear that it works!
