### ISSUE TITLE
install pybinding

### ISSUE THREAD

**Issue by fate118** [dean0x7d/pybinding#13]
Hi Sir,
I want to install pybinding, but this is the error (I have a win64,7):

binding\repository\graphene
    copying pybinding\repository\graphene\utils.py -> build\lib.win-amd64-3.6\py
binding\repository\graphene
    copying pybinding\repository\graphene\__init__.py -> build\lib.win-amd64-3.6
\pybinding\repository\graphene
    creating build\lib.win-amd64-3.6\pybinding\tests
    copying tests\conftest.py -> build\lib.win-amd64-3.6\pybinding\tests
    copying tests\test_kpm.py -> build\lib.win-amd64-3.6\pybinding\tests
    copying tests\test_kwant.py -> build\lib.win-amd64-3.6\pybinding\tests
    copying tests\test_lattice.py -> build\lib.win-amd64-3.6\pybinding\tests
    copying tests\test_leads.py -> build\lib.win-amd64-3.6\pybinding\tests
    copying tests\test_model.py -> build\lib.win-amd64-3.6\pybinding\tests
    copying tests\test_modifiers.py -> build\lib.win-amd64-3.6\pybinding\tests
    copying tests\test_parallel.py -> build\lib.win-amd64-3.6\pybinding\tests
    copying tests\test_pickle.py -> build\lib.win-amd64-3.6\pybinding\tests
    copying tests\test_results.py -> build\lib.win-amd64-3.6\pybinding\tests
    copying tests\test_shape.py -> build\lib.win-amd64-3.6\pybinding\tests
    copying tests\test_solver.py -> build\lib.win-amd64-3.6\pybinding\tests
    copying tests\test_system.py -> build\lib.win-amd64-3.6\pybinding\tests
    copying tests\test_wrapper.py -> build\lib.win-amd64-3.6\pybinding\tests
    copying tests\__init__.py -> build\lib.win-amd64-3.6\pybinding\tests
    running egg_info
    writing pybinding.egg-info\PKG-INFO
    writing dependency_links to pybinding.egg-info\dependency_links.txt
    writing requirements to pybinding.egg-info\requires.txt
    writing top-level names to pybinding.egg-info\top_level.txt
    reading manifest file 'pybinding.egg-info\SOURCES.txt'
    reading manifest template 'setup.manifest'
    no previously-included directories found matching 'cppcore\deps\catch'
    no previously-included directories found matching 'docs\_api'
    no previously-included directories found matching 'tests\failed'
    warning: no previously-included files matching '*.pyc' found anywhere in dis
tribution
    writing manifest file 'pybinding.egg-info\SOURCES.txt'
    copying tests\local.cfg -> build\lib.win-amd64-3.6\pybinding\tests
    creating build\lib.win-amd64-3.6\pybinding\tests\baseline_data
    creating build\lib.win-amd64-3.6\pybinding\tests\baseline_data\kpm
    copying tests\baseline_data\kpm\conductivity[graphene-const_potential].pbz -
> build\lib.win-amd64-3.6\pybinding\tests\baseline_data\kpm
    copying tests\baseline_data\kpm\conductivity[graphene-magnetic_field].pbz ->
 build\lib.win-amd64-3.6\pybinding\tests\baseline_data\kpm
    copying tests\baseline_data\kpm\dos[graphene-const_potential].pbz -> build\l
ib.win-amd64-3.6\pybinding\tests\baseline_data\kpm
    copying tests\baseline_data\kpm\dos[graphene-magnetic_field].pbz -> build\li
b.win-amd64-3.6\pybinding\tests\baseline_data\kpm
    copying tests\baseline_data\kpm\ldos[graphene-const_potential].pbz -> build\
lib.win-amd64-3.6\pybinding\tests\baseline_data\kpm
    copying tests\baseline_data\kpm\ldos[graphene-magnetic_field].pbz -> build\l
ib.win-amd64-3.6\pybinding\tests\baseline_data\kpm
    copying tests\baseline_data\kpm\ldos[graphene-pristine-oversized].pbz -> bui
ld\lib.win-amd64-3.6\pybinding\tests\baseline_data\kpm
    copying tests\baseline_data\kpm\ldos[graphene-pristine].pbz -> build\lib.win
-amd64-3.6\pybinding\tests\baseline_data\kpm
    copying tests\baseline_data\kpm\ldos[mos2].pbz -> build\lib.win-amd64-3.6\py
binding\tests\baseline_data\kpm
    creating build\lib.win-amd64-3.6\pybinding\tests\baseline_data\lattice
    copying tests\baseline_data\lattice\expected[graphene-bilayer].pbz -> build\
lib.win-amd64-3.6\pybinding\tests\baseline_data\lattice
    copying tests\baseline_data\lattice\expected[graphene-monolayer-4atom].pbz -
> build\lib.win-amd64-3.6\pybinding\tests\baseline_data\lattice
    copying tests\baseline_data\lattice\expected[graphene-monolayer-nn].pbz -> b
uild\lib.win-amd64-3.6\pybinding\tests\baseline_data\lattice
    copying tests\baseline_data\lattice\expected[graphene-monolayer].pbz -> buil
d\lib.win-amd64-3.6\pybinding\tests\baseline_data\lattice
    creating build\lib.win-amd64-3.6\pybinding\tests\baseline_data\parallel
    copying tests\baseline_data\parallel\ndsweep.pbz -> build\lib.win-amd64-3.6\
pybinding\tests\baseline_data\parallel
    copying tests\baseline_data\parallel\sweep.pbz -> build\lib.win-amd64-3.6\py
binding\tests\baseline_data\parallel
    creating build\lib.win-amd64-3.6\pybinding\tests\baseline_data\shape
    copying tests\baseline_data\shape\freeform.pbz -> build\lib.win-amd64-3.6\py
binding\tests\baseline_data\shape
    copying tests\baseline_data\shape\polygon_expected[diamond].pbz -> build\lib
.win-amd64-3.6\pybinding\tests\baseline_data\shape
    copying tests\baseline_data\shape\polygon_expected[pentagon].pbz -> build\li
b.win-amd64-3.6\pybinding\tests\baseline_data\shape
    copying tests\baseline_data\shape\polygon_expected[square].pbz -> build\lib.
win-amd64-3.6\pybinding\tests\baseline_data\shape
    copying tests\baseline_data\shape\polygon_expected[triangle90].pbz -> build\
lib.win-amd64-3.6\pybinding\tests\baseline_data\shape
    copying tests\baseline_data\shape\polygon_expected[triangle].pbz -> build\li
b.win-amd64-3.6\pybinding\tests\baseline_data\shape
    creating build\lib.win-amd64-3.6\pybinding\tests\baseline_data\solver
    copying tests\baseline_data\solver\dos[arpack-graphene-magnetic_field].pbz -
> build\lib.win-amd64-3.6\pybinding\tests\baseline_data\solver
    copying tests\baseline_data\solver\dos[feast-graphene-magnetic_field].pbz ->
 build\lib.win-amd64-3.6\pybinding\tests\baseline_data\solver
    copying tests\baseline_data\solver\eigenvalues[arpack-graphene-magnetic_fiel
d].pbz -> build\lib.win-amd64-3.6\pybinding\tests\baseline_data\solver
    copying tests\baseline_data\solver\eigenvalues[feast-graphene-magnetic_field
].pbz -> build\lib.win-amd64-3.6\pybinding\tests\baseline_data\solver
    copying tests\baseline_data\solver\lapack.pbz -> build\lib.win-amd64-3.6\pyb
inding\tests\baseline_data\solver
    copying tests\baseline_data\solver\spatial_ldos[arpack-graphene-magnetic_fie
ld].pbz -> build\lib.win-amd64-3.6\pybinding\tests\baseline_data\solver
    copying tests\baseline_data\solver\spatial_ldos[feast-graphene-magnetic_fiel
d].pbz -> build\lib.win-amd64-3.6\pybinding\tests\baseline_data\solver
    creating build\lib.win-amd64-3.6\pybinding\tests\baseline_data\system
    copying tests\baseline_data\system\expected[graphene-bilayer].pbz -> build\l
ib.win-amd64-3.6\pybinding\tests\baseline_data\system
    copying tests\baseline_data\system\expected[graphene-monolayer-4atom-periodi
c-2d].pbz -> build\lib.win-amd64-3.6\pybinding\tests\baseline_data\system
    copying tests\baseline_data\system\expected[graphene-monolayer-4atom].pbz ->
 build\lib.win-amd64-3.6\pybinding\tests\baseline_data\system
    copying tests\baseline_data\system\expected[graphene-monolayer-alt].pbz -> b
uild\lib.win-amd64-3.6\pybinding\tests\baseline_data\system
    copying tests\baseline_data\system\expected[graphene-monolayer-nn].pbz -> bu
ild\lib.win-amd64-3.6\pybinding\tests\baseline_data\system
    copying tests\baseline_data\system\expected[graphene-monolayer-periodic-1d-a
lt].pbz -> build\lib.win-amd64-3.6\pybinding\tests\baseline_data\system
    copying tests\baseline_data\system\expected[graphene-monolayer-periodic-1d].
pbz -> build\lib.win-amd64-3.6\pybinding\tests\baseline_data\system
    copying tests\baseline_data\system\expected[graphene-monolayer-periodic-2d].
pbz -> build\lib.win-amd64-3.6\pybinding\tests\baseline_data\system
    copying tests\baseline_data\system\expected[graphene-monolayer].pbz -> build
\lib.win-amd64-3.6\pybinding\tests\baseline_data\system
    creating build\lib.win-amd64-3.6\pybinding\tests\baseline_plots
    creating build\lib.win-amd64-3.6\pybinding\tests\baseline_plots\results
    copying tests\baseline_plots\results\structure_map_plot.png -> build\lib.win
-amd64-3.6\pybinding\tests\baseline_plots\results
    creating build\lib.win-amd64-3.6\pybinding\tests\baseline_plots\system
    copying tests\baseline_plots\system\system_plot.png -> build\lib.win-amd64-3
.6\pybinding\tests\baseline_plots\system
    creating build\lib.win-amd64-3.6\pybinding\tests\utils
    copying tests\utils\__init__.py -> build\lib.win-amd64-3.6\pybinding\tests\u
tils
    copying tests\utils\compare_figures.py -> build\lib.win-amd64-3.6\pybinding\
tests\utils
    copying tests\utils\fuzzy_equal.py -> build\lib.win-amd64-3.6\pybinding\test
s\utils
    copying tests\utils\path.py -> build\lib.win-amd64-3.6\pybinding\tests\utils

    running build_ext
    -- Building for: Visual Studio 15 2017
    -- Selecting Windows SDK version 10.0.17134.0 to target Windows 6.1.7601.
    -- The C compiler identification is MSVC 19.15.26732.1
    -- The CXX compiler identification is MSVC 19.15.26732.1
    -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Stu
dio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x64/cl.exe
    -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Stu
dio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x64/cl.exe -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual S
tudio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x64/cl.exe
    -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual S
tudio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x64/cl.exe -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Looking for pthread.h
    -- Looking for pthread.h - not found
    -- Found Threads: TRUE
    -- Downloading eigen3 v3.3.3...
    curl: (52) Empty reply from server
    CMake Error at cppcore/cmake/download.cmake:15 (message):
      Could not download https://bitbucket.org/eigen/eigen/get/3.3.3.tar.gz
    Call Stack (most recent call first):
      cppcore/cmake/download.cmake:24 (download)
      cppcore/cmake/download.cmake:65 (download_tar_gz)
      cppcore/CMakeLists.txt:116 (download_dependency)

    -- Configuring incomplete, errors occurred!
    See also "C:/Users/sana/AppData/Local/Temp/pip-req-build-aohfjani/build/temp
.win-amd64-3.6/Release/CMakeFiles/CMakeOutput.log".
    See also "C:/Users/sana/AppData/Local/Temp/pip-req-build-aohfjani/build/temp
.win-amd64-3.6/Release/CMakeFiles/CMakeError.log".
    -- Building for: Visual Studio 15 2017
    -- Selecting Windows SDK version 10.0.17134.0 to target Windows 6.1.7601.
    -- The C compiler identification is MSVC 19.15.26732.1
    -- The CXX compiler identification is MSVC 19.15.26732.1
    -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Stu
dio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x64/cl.exe
    -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Stu
dio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x64/cl.exe -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual S
tudio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x64/cl.exe
    -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual S
tudio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x64/cl.exe -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Looking for pthread.h
    -- Looking for pthread.h - not found
    -- Found Threads: TRUE
    -- Downloading eigen3 v3.3.3...
    curl: (52) Empty reply from server
    CMake Error at cppcore/cmake/download.cmake:15 (message):
      Could not download https://bitbucket.org/eigen/eigen/get/3.3.3.tar.gz
    Call Stack (most recent call first):
      cppcore/cmake/download.cmake:24 (download)
      cppcore/cmake/download.cmake:65 (download_tar_gz)
      cppcore/CMakeLists.txt:116 (download_dependency)

    -- Configuring incomplete, errors occurred!
    See also "C:/Users/sana/AppData/Local/Temp/pip-req-build-aohfjani/build/temp
.win-amd64-3.6/Release/CMakeFiles/CMakeOutput.log".
    See also "C:/Users/sana/AppData/Local/Temp/pip-req-build-aohfjani/build/temp
.win-amd64-3.6/Release/CMakeFiles/CMakeError.log".
    Traceback (most recent call last):
      File "C:\Users\sana\AppData\Local\Temp\pip-req-build-aohfjani\setup.py", l
ine 74, in build_extension
        build()
      File "C:\Users\sana\AppData\Local\Temp\pip-req-build-aohfjani\setup.py", l
ine 70, in build
        check_call(["cmake", ext.sourcedir] + cmake_args, cwd=self.build_temp, e
nv=env)
      File "c:\programdata\anaconda3\lib\subprocess.py", line 291, in check_call

        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\sana\\AppData\
\Local\\Temp\\pip-req-build-aohfjani', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Use
rs\\sana\\AppData\\Local\\Temp\\pip-req-build-aohfjani\\build\\lib.win-amd64-3.6
', '-DPYTHON_EXECUTABLE=c:\\programdata\\anaconda3\\python.exe', '-DPB_WERROR=OF
F', '-DPB_TESTS=OFF', '-DPB_NATIVE_SIMD=ON', '-DPB_MKL=OFF', '-DPB_CUDA=OFF', '-
DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\sana\\AppData\\Local\\Temp\\p
ip-req-build-aohfjani\\build\\lib.win-amd64-3.6', '-A', 'x64']' returned non-zer
o exit status 1.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\sana\AppData\Local\Temp\pip-req-build-aohfjani\setup.py", l
ine 132, in <module>
        cmdclass=dict(build_ext=CMakeBuild)
      File "c:\programdata\anaconda3\lib\site-packages\setuptools\__init__.py",
line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\programdata\anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\programdata\anaconda3\lib\distutils\dist.py", line 955, in run_co
mmands
        self.run_command(cmd)
      File "c:\programdata\anaconda3\lib\distutils\dist.py", line 974, in run_co
mmand
        cmd_obj.run()
      File "c:\programdata\anaconda3\lib\site-packages\setuptools\command\instal
l.py", line 61, in run
        return orig.install.run(self)
      File "c:\programdata\anaconda3\lib\distutils\command\install.py", line 545
, in run
        self.run_command('build')
      File "c:\programdata\anaconda3\lib\distutils\cmd.py", line 313, in run_com
mand
        self.distribution.run_command(command)
      File "c:\programdata\anaconda3\lib\distutils\dist.py", line 974, in run_co
mmand
        cmd_obj.run()
      File "c:\programdata\anaconda3\lib\distutils\command\build.py", line 135,
in run
        self.run_command(cmd_name)
      File "c:\programdata\anaconda3\lib\distutils\cmd.py", line 313, in run_com
mand
        self.distribution.run_command(command)
      File "c:\programdata\anaconda3\lib\distutils\dist.py", line 974, in run_co
mmand
        cmd_obj.run()
      File "C:\Users\sana\AppData\Local\Temp\pip-req-build-aohfjani\setup.py", l
ine 38, in run
        self.build_extension(ext)
      File "C:\Users\sana\AppData\Local\Temp\pip-req-build-aohfjani\setup.py", l
ine 77, in build_extension
        build()
      File "C:\Users\sana\AppData\Local\Temp\pip-req-build-aohfjani\setup.py", l
ine 70, in build
        check_call(["cmake", ext.sourcedir] + cmake_args, cwd=self.build_temp, e
nv=env)
      File "c:\programdata\anaconda3\lib\subprocess.py", line 291, in check_call

        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\sana\\AppData\
\Local\\Temp\\pip-req-build-aohfjani', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Use
rs\\sana\\AppData\\Local\\Temp\\pip-req-build-aohfjani\\build\\lib.win-amd64-3.6
', '-DPYTHON_EXECUTABLE=c:\\programdata\\anaconda3\\python.exe', '-DPB_WERROR=OF
F', '-DPB_TESTS=OFF', '-DPB_NATIVE_SIMD=ON', '-DPB_MKL=OFF', '-DPB_CUDA=OFF', '-
DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\sana\\AppData\\Local\\Temp\\p
ip-req-build-aohfjani\\build\\lib.win-amd64-3.6', '-A', 'x64']' returned non-zer
o exit status 1.

    ----------------------------------------
Command "c:\programdata\anaconda3\python.exe -u -c "import setuptools, tokenize;
__file__='C:\\Users\\sana\\AppData\\Local\\Temp\\pip-req-build-aohfjani\\setup.p
y';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n
');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\sa
na\AppData\Local\Temp\pip-record-j6a2irnh\install-record.txt --single-version-ex
ternally-managed --compile" failed with error code 1 in C:\Users\sana\AppData\Lo
cal\Temp\pip-req-build-aohfjani\

Any ideas?
Thank you in advance.

**Comment by yixingfu** [comment]
I am having the same problem. How did you solved it?

**Comment by philipesantos136** [comment]
Me too, how solve this?
