### ISSUE TITLE
spin 

### ISSUE THREAD

**Issue by fate118** [dean0x7d/pybinding#15]
i wrote this cod similar  pybinding document page 101-102
import pybinding as pb
import numpy as np
import matplotlib.pyplot as plt

pb.pltutils.use_style()
%matplotlib inline
import pybinding as pb
def s():
    lat = pb.Lattice([1, 0], [0, 1])
    lat.add_sublattices(
         ("A", [0.0, 0.0], 0.5),          # single-orbital: scalar
         ("B", [0.0, 0.2], [[1.5,  2j],   # two-orbital: 2x2 Hermitian matrix
                            [-2j, 1.5]]),
         ("C", [0.3, 0.1], np.zeros(2)),  # two-orbital: zero onsite term
         ("D", [0.1, 0.0], [[4, 0, 0],    # three-orbital: only diagonal
                            [0, 5, 0],
                            [0, 0, 6]]),
         ("E", [0.2, 0.2], [4, 5, 6]))     # three-orbital: only diagonal, terse notation
    
    lat.add_hoppings(
        ([0, 1], "A", "A", 1.2),          # scalar
        ([0, 1], "B", "B", [[1, 2],       # 2x2
                            [3, 4]]),
        ([0, 0], "B", "C", [[2j, 0],      # 2x2
                            [1j, 0]]),
        ([0, 0], "A", "D", [[1, 2, 3]]),  # 1x3
        ([0, 1], "D", "A", [[7],          # 3x1
                            [8],
                            [9]]),
       ([0, 0], "B", "D", [[1j, 0,  0],  # 2x3
                        [2,  0, 3j]]))
    return lat
@pb.onsite_energy_modifier
def potential(energy, x, sub_id):
    """Applies different functions to different sublattices"""
    if sub_id == "A":
        return energy + x  # we know sublattice A is single-orbital
    elif sub_id == "D":
        energy[x > 0] += sub_id.eye * x  # the notation can be mixed with numpy indexing
        return energy                    # apply only to sites where x > 0
    elif sub_id == "B":
        sigma_y = np.array([[0, -1j],
                            [1j,  0]])
        return energy + sigma_y * 1.3 - np.eye(2) * 0.6  # add multiple 2x2 matrices
    else:
        return energy 
lattice=s()
lattice.plot()
plt.show()
model = pb.Model(s(),
                pb.rectangle(4,4),
                potential) 
model.plot()

errore:
boolean index did not match indexed array along dimension 1; dimension is 3 but corresponding boolean dimension is 1

**Comment by fate118** [comment]
please help me

**Comment by fate118** [comment]
why is it error?????????????????/

    elif sub_id == "D":
        energy[x > 0] += sub_id.eye * x  # the notation can be mixed with numpy indexing

**Comment by fate118** [comment]
do error for version python?

**Comment by fate118** [comment]
boolean index did not match indexed array along dimension 1; dimension is 3 but corresponding boolean dimension is 1.
error why??????????????????????????????

**Comment by lise1020** [comment]
Hi, dears:

Can you first normalize your codes like my following example? It is hard for user to debug your codes directly without correct format. See this document too. https://help.github.com/articles/creating-and-highlighting-code-blocks/

```python
import pybinding as pb
from pybinding.repository import graphene

def asymmetric_strain(c):
    @pb.site_position_modifier
    def displacement(x, y, z):
        ux = -c/2 * x**2 + c/3 * x + 0.1
        uy = -c*2 * x**2 + c/4 * x
        return x + ux, y + uy, z
    return displacement

model = pb.Model(
    graphene.bilayer(),
    pb.regular_polygon(num_sides=3, radius=1.1),
    asymmetric_strain(c=0.42)
)
model.plot()
```

**Comment by fate118** [comment]
answer me please

**Comment by fate118** [comment]
I first normalizer  my codes in my program. it is true.

**Comment by fate118** [comment]
when i want to sent you it was wrong. but in my program it is true
