### ISSUE TITLE
coordinates inside displacement function 

### ISSUE THREAD

**Issue by kagb0211** [dean0x7d/pybinding#16]
Hi, 

I would like to generalize displacement(x, y, z) such that ux and uy are read from a list istead of being 
a function of (x,y,z), but I realized that 

x,y,z and ux and uy have a dimension larger than the number of atoms. 

I would expect that the modifier acts on the coordinates of the unstrained model, 
which have coordinates model.system.x with len(model.system.x) = number of atoms. 

I would be glad if you could clarify what x,y,z are and why its values and lengths are different from the unmodified model, in order to understand how to read

 ux, uy from an external list. 
In the following the scipt where the issue is exemplified, 

the aim is to substitute ux with ux_ext inside the function.

Thank you for any advice!
---------------------
[modifier-gen.txt](https://github.com/dean0x7d/pybinding/files/2875968/modifier-gen.txt)

**Comment by BertJorissen** [comment]
The `onsite_modifier`-function will compute the changed positions first, and only then take the appropriate shape. The larger number of sites comes from all the other sites that are first computed, but lie outside the polygon. The function is also called twice, for the A and B sublattice of graphene. The original, distorted and all the sites before the cutout are shown in following figure:
![model](https://user-images.githubusercontent.com/61983794/155408819-0017f0c4-a880-4cee-8595-15b88052f909.png)

We are working on a better implementation of the model class such that this could be used to read out the updated positions from a .xyz-file. This work is still at the first stages, but this will help with the problem you are encountering. Right now, it is harder to tackle this problem. Right now, I just suggest you to print out the values and the sublattice that they correspond to, then, you can change the values manually for that system.
`
