### ISSUE TITLE
Modifiers infinite loop ?

### ISSUE THREAD

**Issue by santoshkumarradha** [dean0x7d/pybinding#21]
Hi, 

Have been playing around with the modifiers inside the model and that seems to send the model on infinite loop.

Creating the model with modifier works fine, but once created, anything from plotting to displaying Hamiltonian starts a infinite loop in the system.

**Comment by zakariaazhar** [comment]
I am facing the same issue!

**Comment by santoshkumarradha** [comment]
One quick solution I found was to downgrade to an older version. 

technically just port the modifier functions to the new one ( I don't know if there is any compatibility issue tho)

**Comment by zakariaazhar** [comment]
Thank you Santosh!, downgrading did not help in my case :(

**Comment by dean0x7d** [comment]
This should be the same issue as #17. Compatibility with Python 3.7+ was fixed in the new v0.9.5 release. Please give it a try.
