### ISSUE TITLE
Build windows

### ISSUE THREAD

**Issue by lcanonico** [dean0x7d/pybinding#22]
Hi, I am having some trouble building from the source in windows, the pip output says that there are undefined function calls, can you give me a little crash course on the windows compilation?

**Comment by chstan** [comment]
Hi @lcanonico,

In case you are dealing with this problem still, I ran into the same issue and could not resolve it. However, I was able to get a workaround by just installing and configuring in an Ubuntu VM on my Windows computer. If you don't already have a VM installed it's definitely an annoying workaround, but a blessing when you run into the second piece of software that won't compile.

In case you're worried about performance running inside a VM, you should expect comparable performance to running on Windows natively. I've run small DFT calculations in this way with no issue in the past.

Best,
Conrad

**Comment by dean0x7d** [comment]
The new v0.9.5 release has a few fixes that should make it easier to compile from source. Please give it a try.
