### ISSUE TITLE
FreeformShape, Composites, and Modifiers on macOS

### ISSUE THREAD

**Issue by zakariaazhar** [dean0x7d/pybinding#23]
Hi all

I am new to pybinding and using macOS. Going through the tutorial everything is going smooth as long as polygns are being used. Problems show up when using  rings , circles, or composite shapes and/or modifiers. Basically, the job does not terminate. I systematically downgraded both python to 3.5 and pybinding down to 0.8, but still facing the same issue. I do not have any similar issues by installing pybinding on windows or linux
Any suggestion?!

**Comment by zakariaazhar** [comment]
Fixed, I had to downgrade miniconda3!

**Comment by santoshkumarradha** [comment]
I messed up my Mac and can't remember what I exactly did to make it work. Can you give in a bit more details ?
What exactly was the problem and which version of the Miniconda did you downgrade to ?
