### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by rodraxphysics** [dean0x7d/pybinding#26]
I used the line: pip install git+https://github.com/dean0x7d/pybinding.git

And I got this error:
Collecting git+https://github.com/dean0x7d/pybinding.git
  Cloning https://github.com/dean0x7d/pybinding.git to c:\users\usuario\appdata\local\temp\pip-req-build-02uqj574
  Running command git clone -q https://github.com/dean0x7d/pybinding.git 'C:\Users\USUARIO\AppData\Local\Temp\pip-req-build-02uqj574'
  ERROR: Error [WinError 2] El sistema no puede encontrar el archivo especificado while executing command git clone -q https://github.com/dean0x7d/pybinding.git 'C:\Users\USUARIO\AppData\Local\Temp\pip-req-build-02uqj574'
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

**Comment by dean0x7d** [comment]
That last line describes the issue: you must install `git`. You can download it here: https://git-scm.com/download/win
