### ISSUE TITLE
Silicon Modelling

### ISSUE THREAD

**Issue by Bhavya1705** [dean0x7d/pybinding#27]
# I am trying to model Silicon using Pybinding, with the code attached below.
( I apologise if this is not the appropriate forum for this question)
##############################################33 
d = 0.543  # [nm] unit cell length
t = 0.17   # [eV] hopping energy
lattice = pb.Lattice(a1=[1,1,0], a2=[0,1,1],a3=[1,0,1])
lattice.add_sublattices(
    ("A",[0,0,0]),
    ("B",[0,1,0]),
    ("C",[0,0,1]),
    ("D",[0,1,1]),
    ("E",[1,0,0]),
    ("F",[1,0,1]),
    ("G",[1,1,1]),
    ("H",[1,1,0]),
    ##################################################333
    ("I",[0,0.5,0.5]),
    ("J",[0.5,0.5,0]),
    ("K",[0.5,0,0.5]),
    ("L",[1,0.5,0.5]),
    ("M",[0.5,0.5,1]),
    ("N",[0.5,1,0.5]),
    ###################################################33
    ("O",[0.75,0.75,0.75]),
    ("P",[0.75,0.25,0.25]),
    ("Q",[0.25,0.75,0.25]),
    ("R",[0.25,0.25,0.75]))
lattice.add_hoppings(
     #(relative_index, from_sublattice, to_sublattice, energy)
    ([0.25, -0.25,0.25], 'Q', 'B', t),
    ([-0.25,-0.25,-0.25], 'Q', 'N', t),
    ([-0.25,0.25,0.25], 'Q', 'J', t),
    ([0.25,0.25,-0.25], 'Q', 'I', t),
    ([-0.25, 0.25,0.25], 'P', 'E', t),
    ([0.25, 0.25,-0.25], 'P', 'K', t),
    ([-0.25,-0.25,-0.25], 'P', 'L', t),
    ([0.25,-0.25,0.25], 'P', 'J', t),
######################################################################33
    ([0.25,0.25,-0.25], 'R', 'C', t),
    ([-0.25,0.25,0.25], 'R', 'K', t),
    ([0.25, -0.25,0.25], 'R', 'I', t),
    ([-0.25, -0.25,-0.25], 'R', 'M', t),
    ([-0.25,-0.25, -0.25], 'O', 'G', t),
    ([0.25,-0.25,0.25 ], 'O', 'N', t),
    ([-0.25,0.25,0.25], 'O', 'L', t),
    ([0.25,0.25,-0.25], 'O', 'M', t)) 
![image](https://user-images.githubusercontent.com/20517886/84689727-004cab80-af5f-11ea-8f1a-a3094f7f3578.png)
## Unfortunately the E-k diagram is not expected, attached below.
![image](https://user-images.githubusercontent.com/20517886/84689815-26724b80-af5f-11ea-9ae0-9c730701d70b.png)
Can anyone point out the error in the code. (As the expected graph should not look like this)

**Comment by dean0x7d** [comment]
I'm not really familiar with the silicon TB model so I can't offer much help here. I'll close this issue since it's related to a specific model and not to the library in general.
