### ISSUE TITLE
Edit the hamilton matrix

### ISSUE THREAD

**Issue by Lordbear2** [dean0x7d/pybinding#28]
Hi.
I have been testing the module with a lattice of kagome and this generated a doubt, the hamilton matrix gives me pure ones but I would like to know if this default matrix can be edited and if this is how I can do it from jupyter lab.
Thank you.

**Comment by dean0x7d** [comment]
The tutorial goes through this step by step, with lots of examples: https://docs.pybinding.site/en/stable/tutorial/index.html It explains how to build and modify a system in various ways.

**Comment by Lordbear2** [comment]
Thanks for answering!!

I think I got the question wrong, my understanding is that the Hamiltonian matrix defaults you to use with graphene, and it works fine for two atoms. But what I want to change is that the Hamiltonian matrix does not give me pure ones but returns values that depend on k.

More or less like the picture
![2020-09-15 (2)](https://user-images.githubusercontent.com/71153412/93271621-5953f780-f779-11ea-8cf0-c7d7dad7fb30.png)

**Comment by dean0x7d** [comment]
You can use [`Model.set_wave_vector()`](https://docs.pybinding.site/en/stable/_api/pybinding.Model.html#pybinding.Model.set_wave_vector). After setting `k` using that method, the next call to `Model.hamiltonian` will produce the adjusted matrix. This isn't covered extensively in the tutorial but there is a little example near the bottom of [the  page dedicated to solvers](https://docs.pybinding.site/en/stable/tutorial/solvers.html). That example uses `Solver.set_wave_vector()` which is just a convenience function that calls `Model.set_wave_vector()` on the model which was given to the solver.
