### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by yxf0125** [dean0x7d/pybinding#29]
Hi, I am relatively new to python so please forgive me.

I tried to install the pybinding under python 3.8 and got some errors.
------------------------------------------------------------------
(base) C:\Windows\system32>pip install pybinding
Collecting pybinding
  Using cached pybinding-0.9.5-cp38-cp38-win_amd64.whl (768 kB)
Requirement already satisfied: pytest>=5.0 in c:\programdata\anaconda3\lib\site-packages (from pybinding) (5.4.3)
Requirement already satisfied: numpy>=1.12 in c:\programdata\anaconda3\lib\site-packages (from pybinding) (1.18.5)
Requirement already satisfied: matplotlib>=2.0 in c:\programdata\anaconda3\lib\site-packages (from pybinding) (3.2.2)
Requirement already satisfied: scipy>=0.19 in c:\programdata\anaconda3\lib\site-packages (from pybinding) (1.5.0)
Requirement already satisfied: py>=1.5.0 in c:\programdata\anaconda3\lib\site-packages (from pytest>=5.0->pybinding) (1.9.0)
Requirement already satisfied: packaging in c:\programdata\anaconda3\lib\site-packages (from pytest>=5.0->pybinding) (20.4)
Requirement already satisfied: attrs>=17.4.0 in c:\programdata\anaconda3\lib\site-packages (from pytest>=5.0->pybinding) (19.3.0)
Requirement already satisfied: more-itertools>=4.0.0 in c:\programdata\anaconda3\lib\site-packages (from pytest>=5.0->pybinding) (8.4.0)
Requirement already satisfied: pluggy<1.0,>=0.12 in c:\programdata\anaconda3\lib\site-packages (from pytest>=5.0->pybinding) (0.13.1)
Requirement already satisfied: wcwidth in c:\programdata\anaconda3\lib\site-packages (from pytest>=5.0->pybinding) (0.2.5)
Requirement already satisfied: atomicwrites>=1.0 in c:\programdata\anaconda3\lib\site-packages (from pytest>=5.0->pybinding) (1.4.0)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from pytest>=5.0->pybinding) (0.4.3)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=2.0->pybinding) (2.4.7)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=2.0->pybinding) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=2.0->pybinding) (1.2.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=2.0->pybinding) (2.8.1)
Requirement already satisfied: six in c:\programdata\anaconda3\lib\site-packages (from packaging->pytest>=5.0->pybinding) (1.15.0)
Installing collected packages: pybinding
Successfully installed pybinding-0.9.5
---------------------------------------------------------------

Although Pybinding shows a successful installation, an error occurs when I run import Pybinding as pb.
It gives me 

---------------------
runfile('C:/Users/Administrator/.spyder-py3/temp.py', wdir='C:/Users/Administrator/.spyder-py3')
Traceback (most recent call last):

  File "C:\Users\Administrator\.spyder-py3\temp.py", line 8, in <module>
    import pybinding as pb

  File "C:\ProgramData\Anaconda3\lib\site-packages\pybinding\__init__.py", line 20, in <module>
    import _pybinding as _cpp

ImportError: DLL load failed while importing _pybinding: The specified module could not be found。
---------------------

I wonder how to deal with the issue.
Thanks.

**Comment by dean0x7d** [comment]
I can't really tell what went wrong. But maybe you could try installing from `conda` instead of `pip`. 

First, uninstall it from `pip`:
```
pip uninstall pybinding
```
Then install from `conda-forge`:
```
conda install -c conda-forge pybinding
```

**Comment by yxf0125** [comment]
> I can't really tell what went wrong. But maybe you could try installing from `conda` instead of `pip`.
> 
> First, uninstall it from `pip`:
> 
> ```
> pip uninstall pybinding
> ```
> 
> Then install from `conda-forge`:
> 
> ```
> conda install -c conda-forge pybinding
> ```

Thank you very much, this question was solved successfully.

**Comment by dean0x7d** [comment]
Glad that helped!
