### ISSUE TITLE
brillouin_zone -> scipy Voronoi segfaults on macos 10.10.5

### ISSUE THREAD

**Issue by denis-bz** [dean0x7d/pybinding#32]
Hi Pybinding people,

8 June: not your problem -- `cd .../scipy/spatial/tests;  pytest test_qhull.py` crashes too, also in scipy 1.7.0rc1 .
https://github.com/scipy/scipy/issues/9858 from 2019 mentions "older versions of Xcode /  MacOS".

<hr>

`brillouin_zone -> scipy Voronoi` segfaults for me, in 0.9.5
with numpy 1.20.3  scipy 1.6.3  python 3.7.9  mac 10.10.5
both in test_brillouin_zone and examples phosphorene --

```
cd .../site/pybinding/tests
pytest -v test_lattice.py::test_brillouin_zone
	platform darwin -- Python 3.7.9, pytest-6.2.4, py-1.10.0, pluggy-0.13.1 -- /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7
	cachedir: .pytest_cache
	rootdir: /opt/local/py3/lib/python3.7/site-packages/pybinding/tests
	collected 1 item                                                                         

	test_lattice.py::test_brillouin_zone Segmentation fault  (no stacktrace ?)


cd .../pybinding-master/docs/examples/lattice
python phosphorene.py
	Fatal Python error: Segmentation fault

	Current thread 0x00007fff75e3e300 (most recent call first):
	  File "/opt/local/py3/lib/python3.7/site-packages/pybinding/lattice.py", line 333 in brillouin_zone
	  File "/opt/local/py3/lib/python3.7/site-packages/pybinding/lattice.py", line 524 in plot_brillouin_zone
	  File "/opt/local/py/pybinding-master/docs/examples/lattice/phosphorene.py", line 72 in <module>

lattice.py:333
            vor = Voronoi([p[:self.ndim] for p in points])
```

Are other platforms ok ? Maybe my old 10.10.5 ?
scipy.spatial.Delaunay crashed for me a couple of years ago, haven't checked if it still does.
Possibly related: https://github.com/scipy/scipy/issues/8929

`conda install cmake numpy scipy matplotlib` in your good `install` doc
didn't help -- how does that differ from just
`pip install numpy scipy matplotlib pybinding` ?

thanks, cheers

**Comment by MAndelkovic** [comment]
Hey Denis,

This indeed sounds like something that can be related to the scipy issue you pointed to. Do the suggestions in the comments help to resolve this issue?
 
The latest release was tested on macos 10.11, with different versions of python (3.6, 3.7, and 3.9). 
What you could do is to take a look at the test configs on travis, and try to replicate the environment for example from [this run](https://travis-ci.org/github/dean0x7d/pybinding/jobs/722484623). You can find more info about the scipy version bellow line 282. 

> `conda install cmake numpy scipy matplotlib` in your good `install` doc
> didn't help -- how does that differ from just
> `pip install numpy scipy matplotlib pybinding` ?

the two would install packages from different repositories, so even if you would specify the same version, you would install a different package.

**Comment by denis-bz** [comment]
Hi Miša
  looks like a macos 10.10 problem, closing -- mttiw, more trouble than it's worth.

An unrelated question, `model.hamiltonian` seems to be always `np.float32`, is that intentional ?
It makes quite a difference, check |AV - VΛ|_max

**Comment by MAndelkovic** [comment]
Hi Denis,

By default the precision is float. If there are no modifiers that would require different type of Hamiltonian, it will stay like that (e.g. adding magnetic field will promote to complex).

On the other hand you can choose (force) higher precision by adding some of the predefined modifiers whose only purpose is to promote the precision. You can see more [here](https://docs.pybinding.site/en/stable/api.html?highlight=force_double_precision#modifiers)
```python
import pybinding as pb
from pybinding.repository import graphene

model_float = pb.Model(
    graphene.monolayer_4atom(),
)
print(model_float.hamiltonian.dtype)

model_double = pb.Model(
    graphene.monolayer_4atom(),
    pb.force_double_precision()
)
print(model_double.hamiltonian.dtype)
```
