### ISSUE TITLE
minimum size of graphene twist bilayers to avoid bulk construction in below 1 degree

### ISSUE THREAD

**Issue by babakabrishamchian** [dean0x7d/pybinding#33]
Hi pybinding friends,
I try to build the bilayer G/G and G/hBN separately, and in building two monolayers for constructing a supercell of twist bilayer graphene I do not know the minimum number of atoms or in another world the minimum size of the circular layer to avoid the bulk structure for a supercell, in DFT usually, a vacuum add to two layers about 20 Angstrom, so for example, is a 1-nanometer radius of layers create a supercell for twist bilayers in angel bellow the 1 degree by using the PYBINDING?
thank you in advance for your guidance and help

**Comment by MAndelkovic** [comment]
Hi there,

These two papers might help to define a unit cell
twisted bilayer graphene: https://repositorium.sdum.uminho.pt/bitstream/1822/21069/4/1202.1088_twist.pdf
graphene on hBN: https://arxiv.org/pdf/1406.0668.pdf
