### ISSUE TITLE
Finite Boundary condition

### ISSUE THREAD

**Issue by ThoPhoton** [dean0x7d/pybinding#34]
Hello everyone,
I have working with the Pybinding for a while, I am interesting in the finite structure. I have the following question:
How does Pybinding handle the boundary condition in the direction where we set to finite? (please see the image below) Is it the boundary condition in Pybinding is the endpoint boundary condition? Thank you in advance!
![shape_symmetry-5](https://user-images.githubusercontent.com/82699531/148955709-7d2eeb55-a0b8-4add-befb-256bc180ccc1.png)

**Comment by BertJorissen** [comment]
In the direction where you set it to _finite_, PyBinding will just add the Hamiltonian elements for each of the hopping and onsite energies without doing anything else. So for the armchair nanoribbon, all the darker atoms will be added as normal, and in the _y_-direction, periodic boundary conditions will be applied where also an additional phase factor _exp(ika)_ will be added to the hoppings.

If you have the amplitudes for the hopping between _H_ and _C_, you could also add hydrogenated edges to the nanoribbon. But in your case (without hydrogenation), the atoms on the _x_-edges only have 2 neighbours.

**Comment by ThoPhoton** [comment]
Thank you so much for your reply and your comments, it is really helpful!
About how we can add the hydrogenated edges to the graphene nanoribbon (or whatever finite materials), I can not found the guide in the tutorial section! Where should I start if I want to add the hydro atom into the edge of the finite material? Thank you!

**Comment by BertJorissen** [comment]
Attaching Hodrogen atoms to the lattice, you also need to add onsite and hopping energies. These things are not library specific questions. For more help, please refer to the Gitter page.
