### ISSUE TITLE
Fermi surface plotting

### ISSUE THREAD

**Issue by vads2301** [dean0x7d/pybinding#36]
Hi everyone, I have started using pybinding a couple days ago and I am having a bit of trouble plotting Fermi surfaces. First of all, is there anyway to do it with the package or is it necessary to do it ''by hand''? Secondly, I was wondering in what basis the set_wave_vector() method assumes the wave vectors given are. I tried reading in the documentation and the basis doesn't seem to be specified. I assumed it was in the cartesian basis, but the resulting Fermi surface seems to be dependant on the reciprocal wave vectors of my model...

**Comment by BertJorissen** [comment]
I'm not sure what system you try to make, but PyBinding focusses mainly on 2D systems (2D in the sense that you have 2 periodic boundary conditions, a multi-layer could also be made).
With _Fermi surfaces_ I immediately think of something in 3D. This kind of 3D-surface is (currently) not supported.
I presume that you want to see where in the reciprocal space the energy bands are located for certain energy values. As far as I'm aware, this is also not (yet) supported.
The `set_wave_vector()`-method of the `solver`-class will set the `k`-value in the reciprocal space in units of _1/nm_. If you then ask for the `eigenvalues` or `eigenvectors`, it will give you those at the given `k`-point.
You could extract all the energy values for different `k`-points and then try to generate this energy contour.

**Comment by vads2301** [comment]
Ok. That is exactly what I did in the end, but I only wondered if there was an easier way to do it, just like with the band structure. Thanks for responding
