### ISSUE TITLE
Divacancy in random

### ISSUE THREAD

**Issue by 200najnazar** [dean0x7d/pybinding#37]
Hi,

I want to create some Di vacancies (two neighboring atoms)but in random in Pybinding. but when I run the script, the left vacancies are not neighbor but both are belong to two different cell.

Do you have any idea?

**Comment by BertJorissen** [comment]
Please refer to the [Gitter.im](https://gitter.im/dean0x7d/pybinding) for questions about specific topics. Also have a look on the [Tutorial](https://docs.pybinding.site/en/stable/tutorial/strain.html) there this question is covered over there. I've given an answer over there on Gitter.

**Comment by 200najnazar** [comment]
Hi,


But your answer is for the double vacancy sites for definite point not in random.


Bests,

Najmeh

________________________________
