### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by nu11us** [dean0x7d/pybinding#4]
## Problem with the installation.

Operating system is Arch Linux, Python version is 3.6.1, Cmake 3.8.2, GCC 7.1.1.

### pip install pybinding
  Running setup.py install for pybinding ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-oz72p0ht/pybinding/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-yjtdpjk5-record/install-record.txt --single-version-externally-managed --compile:

Continued at https://pastebin.com/60iN0tEv

### pip list
appdirs (1.4.3)
cycler (0.10.0)
decorator (4.0.11)
ipython (5.3.0)
ipython-genutils (0.1.0)
jedi (0.10.2)
louis (3.0.0)
matplotlib (2.0.2)
numpy (1.13.0)
packaging (16.8)
pexpect (4.2.1)
pickleshare (0.7.4)
pip (9.0.1)
prompt-toolkit (1.0.14)
ptyprocess (0.5.1)
py (1.4.34)
pycairo (1.13.3)
Pygments (2.2.0)
pygobject (3.24.1)
pyparsing (2.2.0)
pytest (3.1.2)
python-dateutil (2.6.0)
python-libtorrent (1.1.3)
pytz (2017.2)
pyxdg (0.25)
scipy (0.19.0)
setuptools (36.0.1)
simplegeneric (0.8.1)
six (1.10.0)
team (1.0)
traitlets (4.3.2)
wcwidth (0.1.7)

## pacman -Qe
accerciser 3.22.0-2
adapta-gtk-theme 3.90.1.44-1
aircrack-ng 1.2rc4-4
aisleriot 3.22.2-1
alsa-utils 1.1.4-1
anjuta 3.22.0+1+g2bd433c-1
arduino 1:1.8.3-1
arduino-docs 1.6.6-4
atom 1.17.2-1
atomix 3.22.0-1
autoconf 2.69-4
automake 1.15-2
baobab 3.24.0+1+g202d168-1
bash 4.4.012-2
binutils 2.28.0-3
bison 3.0.4-2
brasero 3.12.1-2
bzip2 1.0.6-6
chromium 59.0.3071.86-1
chromium-widevine 1:1.4.8.970-1
coreutils 8.27-1
cower 16-1
cryptsetup 1.7.5-1
cups 2.2.3-1
cups-pdf 3.0.1-1
dconf-editor 3.23.4+48+g9acdf0a-1
devhelp 3.24.0+7+gefb59e2-1
device-mapper 2.02.171-1
dhcpcd 6.11.5-1
dialog 1:1.3_20170509-1
diffutils 3.6-1
dosfstools 4.1-1
e2fsprogs 1.43.4-1
empathy 3.12.12+120+g4a4b45b94-1
eog 3.24.1-1
epiphany 3.24.2-1
evince 3.24.0+8+ga8363215-1
evolution 3.24.2-1
fakeroot 1.21-2
file 5.31-1
file-roller 3.24.1-1
filesystem 2017.03-2
findutils 4.6.0-2
five-or-more 3.22.2-1
flex 2.6.4-1
four-in-a-row 3.22.1-1
gawk 4.1.4-2
gcc 7.1.1-2
gcc-libs 7.1.1-2
gdm 3.24.2-1
gedit 3.22.0+44+ge706c1259-1
gedit-code-assistance 3.16.0+4+gd19b879-1
gettext 0.19.8.1-2
gftp 2.0.19-8
git 2.13.1-1
gitg 3.24.0-1
glibc 2.25-2
gnome-2048 3.22.0+7+ga460b20-1
gnome-backgrounds 3.24.0+2+g755b6f9-1
gnome-builder 3.24.2-1
gnome-calculator 3.24.0+2+g0ca2919b-1
gnome-calendar 3.24.3-1
gnome-characters 3.22.0+49+g0d6a0bd-1
gnome-chess 3.24.1-1
gnome-clocks 3.24.0+4+gd1003cd-1
gnome-code-assistance 3.16.1-1
gnome-contacts 3.22.1+4+gb235b6d-1
gnome-control-center 3.24.2-1
gnome-devel-docs 3.22.1-1
gnome-dictionary 3.24.0+5+ga7aa054-1
gnome-disk-utility 3.24.1-1
gnome-documents 3.24.2-1
gnome-font-viewer 3.24.0-1
gnome-getting-started-docs 3.24.1-1
gnome-keyring 1:3.20.0+57+g9db67ef6-1
gnome-klotski 3.22.1-1
gnome-logs 3.24.1+1+gf949685-1
gnome-mahjongg 3.22.0+1+g55799c1-1
gnome-screenshot 3.22.0+42+g8472361-1
gnome-session 3.24.1-1
gnome-settings-daemon 3.24.2-1
gnome-shell 3.24.2-1
gnome-shell-extension-dash-to-dock 57-1
gnome-shell-extensions 3.24.2-1
gnome-system-monitor 3.24.0+4+g9140c85a-1
gnome-terminal 3.24.2-1
gnome-themes-standard 3.22.3-1
gnome-tweak-tool 3.24.1-1
gnome-user-docs 3.24.2-1
gnome-user-share 3.18.3+2+g7b451ae-1
grep 3.0-1
grilo-plugins 0.3.4+13+gf460a00-1
groff 1.22.3-7
gtk3-print-backends 3.22.15-1
gucharmap 9.0.4-1
gvfs-afc 1.32.1-1
gvfs-goa 1.32.1-1
gvfs-google 1.32.1-1
gvfs-gphoto2 1.32.1-1
gvfs-mtp 1.32.1-1
gvfs-nfs 1.32.1-1
gvfs-smb 1.32.1-1
gzip 1.8-2
hexchat 2.12.4-4
inetutils 1.9.4-5
intel-ucode 20170511-1
iproute2 4.11.0-1
iputils 20161105.1f2bb12-2
jfsutils 1.1.15-4
less 487-1
libgnome-games-support 1.2.0-1
libtool 2.4.6-8
licenses 20140629-2
linux 4.11.4-1
logrotate 3.12.2-1
lvm2 2.02.171-1
m4 1.4.18-1
make 4.2.1-2
man-db 2.7.6.1-2
man-pages 4.11-1
mdadm 4.0-1
mousetweaks 3.12.0-2
mutter 3.24.2+18+g0f7c3f367-1
nano 2.8.4-1
nautilus 3.24.1-1
netctl 1.12-2
networkmanager 1.8.0-1
numix-icon-theme-pack LATEST-1
nvidia-utils 381.22-1
openssh 7.5p1-2
p7zip 16.02-3
pacaur 4.7.5-1
pacman 5.0.1-5
patch 2.7.5-1
pciutils 3.5.4-1
pcmciautils 018-7
pepper-flash 24.0.0.221-1
perl 5.26.0-1
pkg-config 0.29.2-1
procps-ng 3.3.12-1
psmisc 22.21-3
python-pip 9.0.1-2
qbittorrent 3.3.13-1
qt4 4.8.7-20
reiserfsprogs 3.6.25-1
rfkill 0.5-2
s-nail 14.8.16-2
screenfetch 3.8.0-2
sed 4.4-1
shadow 4.4-3
slack-desktop 2.5.1-1
spotify 1.0.49.125-2
sublime-text-dev 3.3126-1
sudo 1.8.20.p2-1
sushi 3.24.0-1
sysfsutils 2.1.0-9
systemd-sysvcompat 232-8
tar 1.29-2
terminator 1.91-5
texinfo 6.3-2
tk 8.6.6-1
tor-browser 6.5.1-1
totem 3.24.0-1
tracker 1.12.0+1+g922c213a5-2
ttf-inconsolata 20151221.480630d-2
usbutils 008-1
util-linux 2.29.2-2
vi 1:070224-2
vino 3.22.0+3+g67773d0-1
vlc 2.2.6-1
vsftpd 3.0.3-3
weechat 1.8-2
wget 1.19.1-2
which 2.21-2
wpa_supplicant 1:2.6-6
xdg-user-dirs-gtk 0.10+9+g5b7efc6-1
xf86-video-intel 1:2.99.917+777+g6babcf15-1
xf86-video-vesa 2.3.4-3
xfsprogs 4.11.0-1
xorg-docs 1.7.1-1
xorg-fonts-100dpi 1.0.3-3
xorg-fonts-75dpi 1.0.3-3
xorg-iceauth 1.0.7-1
xorg-luit 1.1.1-2
xorg-server-devel 1.19.3-2
xorg-server-xdmx 1.19.3-2
xorg-server-xephyr 1.19.3-2
xorg-server-xnest 1.19.3-2
xorg-server-xvfb 1.19.3-2
xorg-server-xwayland 1.19.3-2
xorg-sessreg 1.1.1-1
xorg-smproxy 1.0.6-1
xorg-x11perf 1.6.0-1
xorg-xbacklight 1.2.1-1
xorg-xcmsdb 1.0.5-1
xorg-xcursorgen 1.0.6-1
xorg-xdpyinfo 1.3.2-1
xorg-xdriinfo 1.0.5-2
xorg-xev 1.2.2-1
xorg-xgamma 1.0.6-1
xorg-xhost 1.0.7-1
xorg-xinit 1.3.4-4
xorg-xinput 1.6.2-1
xorg-xkbevd 1.1.4-1
xorg-xkbutils 1.0.4-2
xorg-xkill 1.0.4-1
xorg-xlsatoms 1.1.2-1
xorg-xlsclients 1.1.3-1
xorg-xpr 1.0.4-2
xorg-xrandr 1.5.0-1
xorg-xrefresh 1.0.5-1
xorg-xset 1.2.3-1
xorg-xvinfo 1.1.3-1
xorg-xwd 1.0.6-1
xorg-xwininfo 1.1.3-1
xorg-xwud 1.0.4-2
yelp 3.22.0+1+gfabd8eb-1

Any help would be appreciated, and from what I've seen in the docs this looks like a great tool.

**Comment by dean0x7d** [comment]
Thanks for the detailed report! Looks like this is being caused by a macro name collision in fmtlib, which is used internally by pybinding (related issue: https://github.com/fmtlib/fmt/issues/398). I've updated the bundled version of fmtlib in 974aeb322debda5961b75302b07e239f2d48af1f, which should resolve the compilation problem.

To get the fix, you can install pybinding from the master branch:
```
pip install git+https://github.com/dean0x7d/pybinding.git
```
If it compiles correctly now, you can also run the tests to check everything:
```pycon
>>> import pybinding as pb
>>> pb.tests()
```

Let me know if that did the trick.

**Comment by nu11us** [comment]
Thanks! That worked with sudo. (136 passed in 10.60 seconds)

**Comment by dean0x7d** [comment]
Great, I'm glad to hear everything's working.

**Comment by Simba2805** [comment]
@dean0x7d @MAndelkovic 
I am not able to install the package. I tried this 
`pip install git+https://github.com/dean0x7d/pybinding.git`
 But it showed me an error
`ERROR: Command errored out with exit status 128: git clone -q https://github.com/dean0x7d/pybinding.git 'C:\Users\Shubham\AppData\Local\Temp\pip-req-build-mb4dbpdl' Check the logs for full command output.`

Can you please help me out with this?

**Comment by rodraxphysics** [comment]
> @dean0x7d @MAndelkovic
> I am not able to install the package. I tried this
> `pip install git+https://github.com/dean0x7d/pybinding.git`
> But it showed me an error
> `ERROR: Command errored out with exit status 128: git clone -q https://github.com/dean0x7d/pybinding.git 'C:\Users\Shub\AppData\Local\Temp\pip-req-build-mb4dbpdl' Check the logs for full command output.`
> 
> Can you please help me out with this?

i have the same problem
