### ISSUE TITLE
Small question about heatmap-plot of the eigenvalue.

### ISSUE THREAD

**Issue by ChenqiangHua** [dean0x7d/pybinding#45]
Dear developers,

Recently  i try to use the 'solver.calc_eigenvalues' to map the distributiuon of some satets after solving the model. Detials see below:
%%%
solver = pb.solver.lapack(model)
eigen=solver.calc_eigenvalues(map_probability_at=[XX,XX])
eigen.plot_heatmap()
%%%%
The output is beautiful. But I also want to change the x and y limition (in a larged view) as nomally done in the plt.plot, such as "ax.set_xlim(-0.2,0.2)".   
In the Docs (https://docs.pybinding.site/en/stable/_api/pybinding.Eigenvalues.html?highlight=plot_heatmap#pybinding.Eigenvalues.plot_heatmap),  I cannot find the tag to change this?   Can u help me about this?

**Comment by BertJorissen** [comment]
Hi Chenqiang
I'm not certain if you really want to use the _map_probability_at_-function. This function tries to select the state in the wavefunction (set of eigenvectors) that co insides with the selected position, and gives the probability of that state (eigenvector). You thus only see a selection of the wavefunction.
We are currently working on a new release. You can download the new release by first removing your old version of Pybinding with `pip uninstall pybinding` and then running `pip install -i https://test.pypi.org/simple/ pybinding`.
In the new version, you have the possibility to calculate the wavefunction and a lot of new interesting things.

Regarding your question: the plot you get is a kind of scatter plot with some interesting decorations. It just puts all the eigenvalues from 0 to 100 on a plot. I think this is not that interesting at all, but the functionality is there if you want to use it. I rather suggest using the spatial-LDOS. Now, you can calculate the wavefunction over an area and obtain an accurate approximation for this.

You can obtain the current axis in matplotlib with **`ax=plt.gca()`**. The rest works as expected.

Bellow an example of the new functionalities:
```
import pybinding as pb
import numpy as np
import matplotlib.pyplot as plt
from pybinding.repository.graphene import bilayer

def asymmetric_strain(c):
    @pb.site_position_modifier
    def displacement(x, y, z):
        ux = -c/2 * x**2 + c/3 * x + 0.1
        uy = -c*2 * x**2 + c/4 * x
        return x + ux, y + uy, z
    return displacement

model = pb.Model(bilayer(), pb.regular_polygon(num_sides=3, radius=1.1), asymmetric_strain(c=0.42))

solver = pb.solver.lapack(model)
eigen = solver.calc_eigenvalues(map_probability_at=[0,0])

fig, (ax1, ax2) = plt.subplots(2)
eigen.plot_heatmap(ax=ax2)
ax2.set_xlim([20, 100])
ax2.set_ylim([-5, 5])

wfc = solver.calc_wavefunction([0, 0], [0, .1])
sldos = wfc.spatial_ldos(np.linspace(-1, 1, 100), 0.05)
sldos.structure_map(0).plot(ax=ax1)
```
![wfc](https://github.com/dean0x7d/pybinding/assets/61983794/16d56db5-0028-4f92-be23-b6466cd0a5eb)
Best
Bert

**Comment by ChenqiangHua** [comment]
**Thanks sir!** I have installed the new version and it fixs my question well!   I can't wait to explore new interesting things in this new version.

Thx again!
Chenqiang Hua
