### ISSUE TITLE
 ERROR: Failed building wheel for pybinding

### ISSUE THREAD

**Issue by jaimegarridoaldea** [dean0x7d/pybinding#53]
Hi! 

I am trying to install pybinding on my existing miniconda environment (the one I use for basically all my work). I am trying to do so with pip install pybinding
but with no success (Details ahead). The installation works in another miniconda environment I do not use, but for me it is essential to use pybinding in my usual environment. The error I get in the installation is:

 Building wheel for pybinding (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1

A LOT OF TEXT

 note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pybinding
  Running setup.py clean for pybinding
Failed to build pybinding
ERROR: Could not build wheels for pybinding, which is required to install pyproject.toml-based projects

Any idea on how I can fix this? I am such a dummy for technical stuff. I have also tried with the other suggested installation methods but they did not work.

Suggestions?

Thanks in advance

**Comment by BertJorissen** [comment]
Hi
I'll update the pip installation next year, but for now, you ca install pybinding using the following commands:
- pip install numpy scipy matplotlib pytest
- pip install -i https://test.pypi.org/simple/ pybinding

This is not yet for 3.12, you'll have to downgrade to an earlier version of python.
Let me know if it works.
Best
Bert

**Comment by jaimegarridoaldea** [comment]
It works now!

Thanks a lot Bert!
