### ISSUE TITLE
Difficulty installing locally (windows 11 & wsl)

### ISSUE THREAD

**Issue by Astech34** [dean0x7d/pybinding#59]
I can run PyBinding in google colab just fine, but I'm trying to install locally through pip and its having trouble building the wheel.

I've tried it first using anaconda on windows and then again with miniconda on Ubunutu WSL, and get the same error.

Here is output (for WSL)
https://pastebin.com/955p8ffd

Thanks!

**Comment by BertJorissen** [comment]
Pybinding (main release) is hopelessly outdated, but mainly the link with pybind11. I'm waiting for @dean0x7d to give me access to to full repo and pypi to fix this.

For the time being, you can use the development version at 'pip install pybinding-dev'.

This version uses a pre-build distribution, but there are still some issues on Mac /windows I'll sort out next week. Normally, this version should work fine if you run the 'pip install pybinding-dev --no-binary' command.

Let me know if you encounter some problems.
Best
Bert

**Comment by BertJorissen** [comment]
From your files, it seems that you haven't set a compiler. A new version would not really solve this. If you want to install pybinding on Linux, you also need the 'python-dev' and 'build-essential' packages which you can find on apt.

**Comment by Astech34** [comment]
Running "pip install pybinding-dev" works.

Thanks a bunch!
