### ISSUE TITLE
Question about the TMD code

### ISSUE THREAD

**Issue by khaledb9** [dean0x7d/pybinding#63]
Hello 

In https://github.com/dean0x7d/pybinding/blob/master/pybinding/repository/group6_tmd.py line 99, how was h2 and h3 obtained? I cant seem to find the transformations in the paper or in the manual. A guidance from your side is appreciated

Thanks

**Comment by BertJorissen** [comment]
Hi, the entries in the Liu paper are the full 'Hamiltonian' entries, whereas the entries in Pybinding are the pure onsite/hopping energies between the different orbitals.
You can't compare them to each other. However, have a look at my paper (https://scipost.org/SciPostPhysCore.7.1.004) where I made a generic implementation. In essence, the hopping values are transformed slightly (t1, t2 etc) in the paper from Liu to be more in line with a general implementation as  given by Fang. 

The 'h2' and 'h3' are thus just the hopping energies or fourier transform of the Hamiltonian in the direction of the hoppings.
You should try writing them out, though it's easier to start with a simple graphene example.

The matrices 'h1', 'h2' and 'h3 are also just the rotated matrices over an angle of 120 degrees. As the basis is composed of dz2 and 2 d2 orbitals, they rotate into one another. You can see the details in the paper ;).

(Pybinding is software, this is a physics question)
