### ISSUE TITLE
plot hopping strength

### ISSUE THREAD

**Issue by AlMrvn** [dean0x7d/pybinding#8]
Hello,
First of all, thank you for the great work on this package!

I was playing around with the strained model given in the tutorial section and at some point I wanted to plot the strength of the hopping term on a finite systeme. 
I couldn't find any simple way to access the hopping except by directly using the model.Hamiltonian.
Is there a easier way to plot the hopping strength?

**Comment by BertJorissen** [comment]
The plotting of the 'hopping strength' is a hard question. This could be a map in the x/y-space, but then you should also know that there can be multiple orbitals at the same position. As such, this functionality would already break with multiple-orbital models like advanced models for graphene or the models for TMDs. Also, there could be on-site hopping between the same positions of the system. It would be 

Though, we will look into adding this kind of functionality one way or another, there is can be useful to see how the dependence of the model changes with space.
